name: Client workflow pipeline

on:
  push:
    branches:
      - Master

jobs:
  Install-Dependencies-And-Start-Server:
    runs-on: ubuntu-latest
    steps:
      - name: Development code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npm install
      - run: npm start

  Deploy:
    runs-on: ubuntu-latest
    needs: [Install-Dependencies-And-Start-Server]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'client-bookstore-udweb'
          heroku_email: 'builehoangnhattruong@gmail.com'
        
  
